// Generated by Selenium IDE

package Tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("pancakes");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".bkWMgd:nth-child(2) .g:nth-child(1) .LC20lb")).click();
    assertThat(driver.findElement(By.id("recipe-main-content")).getText(), is("Good Old Fashioned Pancakes"));
  }
}
